# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_BCMDHD)	+= rkwifi/
obj-$(CONFIG_AIC_WLAN_SDIO_SUPPORT)	+= aic8800_sdio/
obj-$(CONFIG_AIC_WLAN_USB_SUPPORT)	+= aic8800_usb/
obj-$(CONFIG_RTL8189FS)	+= rtl8189fs/
obj-$(CONFIG_RTL8821CU)	+= rtl8821cu/
obj-$(CONFIG_RTL8851BE)	+= rtl8851be/
obj-$(CONFIG_RTL8852BE)	+= rtl8852be/