# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_CPU_RK3528) += rk3528-lubancat-generic.dtb
dtb-$(CONFIG_CPU_RK3528) += rk3528-lubancat-q1.dtb
dtb-$(CONFIG_CPU_RK3528) += rk3528-lubancat-q1io.dtb

dtb-$(CONFIG_CPU_RK3562) += rk3562-lubancat-generic.dtb
dtb-$(CONFIG_CPU_RK3562) += rk3562-lubancat-1hs.dtb
dtb-$(CONFIG_CPU_RK3562) += rk3562-lubancat-1hs-test.dtb

dtb-$(CONFIG_CPU_RK3568) += rk356x-lubancat-generic.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3566-lubancat-0.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3566-lubancat-1.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3566-lubancat-1h.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3566-lubancat-1n.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3566-lubancat-1io.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3568-lubancat-2.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3568-lubancat-2-v1.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3568-lubancat-2-v2.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3568-lubancat-2-v3.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3568-lubancat-2n.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3568-lubancat-2n-v2.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3568-lubancat-2n-v3.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3568-lubancat-2io.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3568-lubancat-2h.dtb
dtb-$(CONFIG_CPU_RK3568) += rk3566-lubancat-cm4.dtb

dtb-$(CONFIG_CPU_RK3576) += rk3576-lubancat-generic.dtb
dtb-$(CONFIG_CPU_RK3576) += rk3576-lubancat-3.dtb
dtb-$(CONFIG_CPU_RK3576) += rk3576-lubancat-3-v2.dtb
dtb-$(CONFIG_CPU_RK3576) += rk3576-lubancat-3io.dtb
dtb-$(CONFIG_CPU_RK3576) += rk3576-lubancat-3-ddr-emmc-test.dtb
dtb-$(CONFIG_CPU_RK3576) += rk3576-lubancat-3io-test.dtb

dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-generic.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5-v2.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5io.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5ioi.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5iob.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5iof.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588-lubancat-5iobi.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588s-lubancat-4.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588s-lubancat-4-v1.dtb
dtb-$(CONFIG_CPU_RK3588) += rk3588s-lubancat-4io.dtb

subdir-y	:= $(dts-dirs) overlay

